// ============================================================
// lib/ghlPanelSync.js — Live updater for Empírika GHL panel fields.
//
// Used by:
//   - index.js /api/track/open route → set empirika_email_opened_at
//   - workers/followup_touch2_cron.js → set empirika_followup_touch_2_at
//
// Contract:
//   setPanelFieldByLeadId(leadId, hint, value) → void (fire-and-forget)
//
// Never throws. Logs warnings on missing creds / no contact / API error.
// Idempotency: GHL custom field update is itself idempotent (PUT
// overwrites), so re-firing is harmless.
//
// Field hint → GHL fieldKey map is loaded from lib/ghl_panel_fields.json
// at module load (generated by scripts/ghl_create_panel_fields.js).
// ============================================================

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { supabase } from './supabase.js';
import { logger } from './logger.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PANEL_FIELDS_PATH = path.join(__dirname, 'ghl_panel_fields.json');

const GHL_BASE = 'https://services.leadconnectorhq.com';
const LOCATION_ID = process.env.EMPIRIKA_GHL_LOCATION_ID || 'uQPxZOmT4zVlMHfOGRw2';

// Build hint → fieldKey lookup once at module load.
// JSON file format: { fields: { "emprika__<key>": { id, dataType, name } } }
// We accept both 'empirika_<key>' (app-side hint) and 'emprika__<key>'
// (GHL fieldKey) to be forgiving with callers.
let HINT_TO_KEY = {};
try {
  const raw = JSON.parse(fs.readFileSync(PANEL_FIELDS_PATH, 'utf-8'));
  const fields = raw.fields || {};
  for (const ghlKey of Object.keys(fields)) {
    HINT_TO_KEY[ghlKey] = ghlKey;
    // 'emprika__email_opened_at' → 'empirika_email_opened_at'
    const appHint = ghlKey.replace(/^emprika__/, 'empirika_');
    HINT_TO_KEY[appHint] = ghlKey;
  }
} catch (err) {
  logger.warn('[ghlPanelSync] could not load ghl_panel_fields.json', { error: err?.message });
}

function getHeaders() {
  return {
    Authorization: `Bearer ${process.env.EMPIRIKA_GHL_KEY}`,
    Version: '2021-04-15',
    'Content-Type': 'application/json',
    Accept: 'application/json',
  };
}

async function findContactByEmail(email) {
  if (!email) return null;
  const url = new URL(`${GHL_BASE}/contacts/`);
  url.searchParams.set('locationId', LOCATION_ID);
  url.searchParams.set('query', email);
  url.searchParams.set('limit', '5');
  const res = await fetch(url.toString(), { headers: getHeaders() });
  if (!res.ok) return null;
  const body = await res.json().catch(() => ({}));
  const list = body?.contacts || [];
  return list.find(c => (c.email || '').toLowerCase() === email.toLowerCase()) || list[0] || null;
}

async function updateContactFields(contactId, customFields) {
  const res = await fetch(`${GHL_BASE}/contacts/${contactId}`, {
    method: 'PUT',
    headers: getHeaders(),
    body: JSON.stringify({ customFields }),
  });
  if (!res.ok) {
    const t = await res.text().catch(() => '');
    return { ok: false, status: res.status, error: t.slice(0, 200) };
  }
  return { ok: true };
}

/**
 * Set a single panel field on the GHL contact matching this lead.
 * Fire-and-forget — never throws.
 *
 * @param {string} leadId — UUID of the lead in public.leads
 * @param {string} hint   — fieldKey hint (e.g. 'empirika_email_opened_at')
 * @param {string|number|Date} value — value to write (Date → ISO string)
 */
export async function setPanelFieldByLeadId(leadId, hint, value) {
  try {
    if (!process.env.EMPIRIKA_GHL_KEY) return;
    if (!leadId || !hint) return;

    const ghlKey = HINT_TO_KEY[hint] || HINT_TO_KEY[`empirika_${hint}`];
    if (!ghlKey) {
      logger.warn('[ghlPanelSync] unknown hint', { hint });
      return;
    }

    if (!supabase) return;
    const { data: lead, error } = await supabase
      .from('leads')
      .select('email_address, email')
      .eq('id', leadId)
      .maybeSingle();
    if (error || !lead) return;

    const email = lead.email_address || lead.email;
    if (!email) return;

    const contact = await findContactByEmail(email);
    if (!contact?.id) return;

    const formatted = value instanceof Date ? value.toISOString() : value;
    const customFields = [{ key: ghlKey, field_value: formatted }];

    const upd = await updateContactFields(contact.id, customFields);
    if (!upd.ok) {
      logger.warn('[ghlPanelSync] update failed', { hint, status: upd.status, error: upd.error });
    } else {
      logger.info('[ghlPanelSync] field set', { lead_id: leadId, hint, value: String(formatted).slice(0, 60) });
    }
  } catch (err) {
    logger.warn('[ghlPanelSync] silent error', { error: err?.message });
  }
}

/**
 * Internal: expose lookup table for tests.
 */
export function _hintToKey() {
  return { ...HINT_TO_KEY };
}
