// ============================================================
// lib/llmPricing.js — LLM provider pricing table
//
// Used by: lib/costTracker.js to calculate token costs
// ============================================================

const PRICING = {
  // NVIDIA (deployed via services.jina.ai or similar)
  nvidia: {
    input_per_1m_tokens: 0.6,
    output_per_1m_tokens: 1.8,
  },
  // Google Gemini (Flash)
  gemini_flash: {
    input_per_1m_tokens: 0.075,
    output_per_1m_tokens: 0.3,
  },
  // Anthropic Claude (if used)
  claude: {
    input_per_1m_tokens: 3.0,
    output_per_1m_tokens: 15.0,
  },
  // Default fallback
  default: {
    input_per_1m_tokens: 0.3,
    output_per_1m_tokens: 1.2,
  },
};

/**
 * Calculate cost for a single LLM API call
 * @param {string} provider - 'nvidia', 'gemini_flash', 'claude', etc.
 * @param {number} inputTokens - tokens consumed by input
 * @param {number} outputTokens - tokens generated by model
 * @returns {number} - cost in USD
 */
export function calculateLlmCost(provider, inputTokens, outputTokens) {
  const pricing = PRICING[provider] || PRICING.default;
  const inputCost = (inputTokens / 1_000_000) * pricing.input_per_1m_tokens;
  const outputCost = (outputTokens / 1_000_000) * pricing.output_per_1m_tokens;
  return inputCost + outputCost;
}

/**
 * Get pricing for a given provider
 * @param {string} provider - provider name
 * @returns {object} - pricing object { input_per_1m_tokens, output_per_1m_tokens }
 */
export function getPricing(provider) {
  return PRICING[provider] || PRICING.default;
}

export default {
  PRICING,
  calculateLlmCost,
  getPricing,
};
